version: '3.7'

services:
  spring-batch-db:
    image: mysql:8
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=batch
      - MYSQL_PASSWORD=testing

  card-db:
    image: mysql:8
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=card
      - MYSQL_PASSWORD=testing

  account-db:
    image: mysql:8
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=account
      - MYSQL_PASSWORD=testing
      
  spring-batch:
    image: kwonghung/spring-batch-multi-datasource:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker-compose
    depends_on:
      - spring-batch-db
      - card-db
      - account-db
    
      
