name: Build project and docker image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/setup-java@v1
      - name: Set up JDK 1.8
        with:
          java-version: 1.8
      - name: Build with Maven
        run: |
          pwd
          ls -l
          ./mvnw -B clean build
